version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: accounting_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: accounting-system
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/accounting_system?allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_USERNAME: admin
    ports:
      - "8082:8082"
    depends_on:
      - mysql

volumes:
  db-data: