version: '3.8'

services:
  mysql:
    image: "mysql:8.0"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=accounting_system
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3307:3306"
    volumes:
      - "db-data:/var/lib/mysql/data"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'accounting-system'
    ports:
      - "8082:8082"
    depends_on:
      - mysql

volumes:
  db-data: